/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/router';
import * as i3 from '@angular/common';
import * as i4 from './app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['',''])),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
      ['¡Hola i18n!'])),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),15,'nav',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),5,'a',[['routerLink','/dashboard'],['routerLinkActive',
          'active']],[[1,'target',0],[8,'href',4]],[[(null as any),'click']],(_v,en,
          $event) => {
        var ad:boolean = true;
        if (('click' === en)) {
          const pd_0:any = ((<any>i1.ɵnov(_v,9).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i1.ɵdid(671744,[[2,4]],0,i2.RouterLinkWithHref,
      [i2.Router,i2.ActivatedRoute,i3.LocationStrategy],{routerLink:[0,'routerLink']},
      (null as any)),i1.ɵdid(1720320,(null as any),2,i2.RouterLinkActive,[i2.Router,
      i1.ElementRef,i1.Renderer2,i1.ChangeDetectorRef],{routerLinkActive:[0,'routerLinkActive']},
      (null as any)),i1.ɵqud(603979776,1,{links:1}),i1.ɵqud(603979776,2,{linksWithHrefs:1}),
      (_l()(),i1.ɵted((null as any),['Dashboard'])),(_l()(),i1.ɵted((null as any),
          ['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),5,'a',[['routerLink',
          '/heroes'],['routerLinkActive','active']],[[1,'target',0],[8,'href',4]],
          [[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            if (('click' === en)) {
              const pd_0:any = ((<any>i1.ɵnov(_v,16).onClick($event.button,$event.ctrlKey,
                  $event.metaKey,$event.shiftKey)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),i1.ɵdid(671744,[[4,4]],0,i2.RouterLinkWithHref,
          [i2.Router,i2.ActivatedRoute,i3.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),i1.ɵdid(1720320,(null as any),2,i2.RouterLinkActive,[i2.Router,
          i1.ElementRef,i1.Renderer2,i1.ChangeDetectorRef],{routerLinkActive:[0,'routerLinkActive']},
          (null as any)),i1.ɵqud(603979776,3,{links:1}),i1.ɵqud(603979776,4,{linksWithHrefs:1}),
      (_l()(),i1.ɵted((null as any),['Heroes'])),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(16777216,(null as any),
          (null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),i1.ɵdid(212992,(null as any),
          0,i2.RouterOutlet,[i2.ChildrenOutletContexts,i1.ViewContainerRef,i1.ComponentFactoryResolver,
              [8,(null as any)],i1.ChangeDetectorRef],(null as any),(null as any)),
      (_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    const currVal_3:any = '/dashboard';
    _ck(_v,9,0,currVal_3);
    const currVal_4:any = 'active';
    _ck(_v,10,0,currVal_4);
    const currVal_7:any = '/heroes';
    _ck(_v,16,0,currVal_7);
    const currVal_8:any = 'active';
    _ck(_v,17,0,currVal_8);
    _ck(_v,24,0);
  },(_ck,_v) => {
    var _co:i4.AppComponent = _v.component;
    const currVal_0:any = _co.title;
    _ck(_v,1,0,currVal_0);
    const currVal_1:any = i1.ɵnov(_v,9).target;
    const currVal_2:any = i1.ɵnov(_v,9).href;
    _ck(_v,8,0,currVal_1,currVal_2);
    const currVal_5:any = i1.ɵnov(_v,16).target;
    const currVal_6:any = i1.ɵnov(_v,16).href;
    _ck(_v,15,0,currVal_5,currVal_6);
  });
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(49152,(null as any),0,i4.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i4.AppComponent> = i1.ɵccf('app-root',
    i4.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvcnN1YnJhbWFuaWFuL0RvY3VtZW50cy9Bbmd1bGFyVHJhaW5pbmcvV2syL2kxOG5OZXcvc3JjL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL3JzdWJyYW1hbmlhbi9Eb2N1bWVudHMvQW5ndWxhclRyYWluaW5nL1drMi9pMThuTmV3L3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL3JzdWJyYW1hbmlhbi9Eb2N1bWVudHMvQW5ndWxhclRyYWluaW5nL1drMi9pMThuTmV3L3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvcnN1YnJhbWFuaWFuL0RvY3VtZW50cy9Bbmd1bGFyVHJhaW5pbmcvV2syL2kxOG5OZXcvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT57e3RpdGxlfX08L2gxPlxyXG48aDEgaTE4bj1cIkFuIGludHJvZHVjdGlvbiBoZWFkZXIgZm9yIHRoaXMgc2FtcGxlQEBpbnRyb2R1Y3Rpb25IZWFkZXJcIj5IZWxsbyBpMThuITwvaDE+XHJcbjxuYXY+XHJcbiAgPGEgcm91dGVyTGluaz1cIi9kYXNoYm9hcmRcIiByb3V0ZXJMaW5rQWN0aXZlPVwiYWN0aXZlXCI+RGFzaGJvYXJkPC9hPlxyXG4gIDxhIHJvdXRlckxpbms9XCIvaGVyb2VzXCIgcm91dGVyTGlua0FjdGl2ZT1cImFjdGl2ZVwiPkhlcm9lczwvYT5cclxuPC9uYXY+XHJcbjxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD5cclxuIiwiPGFwcC1yb290PjwvYXBwLXJvb3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBLHlCQUFjLHVDQUNsQjthQUFBO1VBQUEsNENBREE7TUFBQSxrQkFDc0YsdUNBQ3RGO01BQUE7TUFBQSw4QkFBSyx5Q0FDSDthQUFBO1VBQUE7Z0JBQUE7UUFBQTtRQUFBO1VBQUE7Y0FBQTtVQUFBO1FBQUE7UUFBQTtNQUFBLHVDQUFBO01BQUE7TUFBQSxzQkFBQTtxREFBQTtNQUFBO01BQXFELDhDQUFhO1VBQUEsV0FDbEU7VUFBQTtVQUFBO1lBQUE7WUFBQTtjQUFBO2tCQUFBO2NBQUE7WUFBQTtZQUFBO1VBQUEsdUNBQUE7VUFBQTtVQUFBLHNCQUFBO3lEQUFBO1VBQUE7TUFBa0QsMkNBQVU7TUFDeEQsdUNBQ047VUFBQTtVQUFBLG1EQUFBO1VBQUE7Y0FBQTtNQUErQjtJQUgxQjtJQUFILFdBQUcsU0FBSDtJQUEyQjtJQUEzQixZQUEyQixTQUEzQjtJQUNHO0lBQUgsWUFBRyxTQUFIO0lBQXdCO0lBQXhCLFlBQXdCLFNBQXhCO0lBRUY7OztJQU5JO0lBQUE7SUFHRjtJQUFBO0lBQUEsV0FBQSxtQkFBQTtJQUNBO0lBQUE7SUFBQSxZQUFBLG1CQUFBOzs7O29CQ0pGO01BQUE7YUFBQTs7OzsifQ==
