/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './dashboard.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/router';
import * as i3 from '@angular/common';
import * as i4 from './hero-search.component.ngfactory';
import * as i5 from './hero-search.service';
import * as i6 from '@angular/http';
import * as i7 from './hero-search.component';
import * as i8 from './dashboard.component';
import * as i9 from './hero.service';
const styles_DashboardComponent:any[] = [i0.styles];
export const RenderType_DashboardComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_DashboardComponent,data:{}});
function View_DashboardComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),9,'div',[['class',
      'col-1-4']],(null as any),[[(null as any),'click']],(_v,en,$event) => {
    var ad:boolean = true;
    if (('click' === en)) {
      const pd_0:any = ((<any>i1.ɵnov(_v,1).onClick()) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any))),i1.ɵdid(16384,(null as any),0,i2.RouterLink,[i2.Router,
      i2.ActivatedRoute,[8,(null as any)],i1.Renderer2,i1.ElementRef],{routerLink:[0,
      'routerLink']},(null as any)),i1.ɵpad(2),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',[['class','module hero']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n      '])),(_l()(),i1.ɵeld(0,(null as any),
          (null as any),1,'h4',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['',''])),(_l()(),
          i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵted((null as any),['\n  ']))],
      (_ck,_v) => {
        const currVal_0:any = _ck(_v,2,0,'/detail',_v.context.$implicit.id);
        _ck(_v,1,0,currVal_0);
      },(_ck,_v) => {
        const currVal_1:any = _v.context.$implicit.name;
        _ck(_v,7,0,currVal_1);
      });
}
export function View_DashboardComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h3',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['Top Heroes'])),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',[['class','grid grid-pad']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵand(16777216,(null as any),
          (null as any),1,(null as any),View_DashboardComponent_1)),i1.ɵdid(802816,
          (null as any),0,i3.NgForOf,[i1.ViewContainerRef,i1.TemplateRef,i1.IterableDiffers],
          {ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          2,'hero-search',([] as any[]),(null as any),(null as any),(null as any),
          i4.View_HeroSearchComponent_0,i4.RenderType_HeroSearchComponent)),i1.ɵprd(512,
          (null as any),i5.HeroSearchService,i5.HeroSearchService,[i6.Http]),i1.ɵdid(114688,
          (null as any),0,i7.HeroSearchComponent,[i5.HeroSearchService,i2.Router],
          (null as any),(null as any)),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,
      _v) => {
    var _co:i8.DashboardComponent = _v.component;
    const currVal_0:any = _co.heroes;
    _ck(_v,6,0,currVal_0);
    _ck(_v,11,0);
  },(null as any));
}
export function View_DashboardComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'my-dashboard',
      ([] as any[]),(null as any),(null as any),(null as any),View_DashboardComponent_0,
      RenderType_DashboardComponent)),i1.ɵdid(114688,(null as any),0,i8.DashboardComponent,
      [i9.HeroService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const DashboardComponentNgFactory:i1.ComponentFactory<i8.DashboardComponent> = i1.ɵccf('my-dashboard',
    i8.DashboardComponent,View_DashboardComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvcnN1YnJhbWFuaWFuL0RvY3VtZW50cy9Bbmd1bGFyVHJhaW5pbmcvV2syL2kxOG5OZXcvc3JjL2FwcC9kYXNoYm9hcmQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL3JzdWJyYW1hbmlhbi9Eb2N1bWVudHMvQW5ndWxhclRyYWluaW5nL1drMi9pMThuTmV3L3NyYy9hcHAvZGFzaGJvYXJkLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL3JzdWJyYW1hbmlhbi9Eb2N1bWVudHMvQW5ndWxhclRyYWluaW5nL1drMi9pMThuTmV3L3NyYy9hcHAvZGFzaGJvYXJkLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvcnN1YnJhbWFuaWFuL0RvY3VtZW50cy9Bbmd1bGFyVHJhaW5pbmcvV2syL2kxOG5OZXcvc3JjL2FwcC9kYXNoYm9hcmQuY29tcG9uZW50LnRzLkRhc2hib2FyZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMz5Ub3AgSGVyb2VzPC9oMz5cclxuPGRpdiBjbGFzcz1cImdyaWQgZ3JpZC1wYWRcIj5cclxuICA8ZGl2ICpuZ0Zvcj1cImxldCBoZXJvIG9mIGhlcm9lc1wiIFtyb3V0ZXJMaW5rXT1cIlsnL2RldGFpbCcsIGhlcm8uaWRdXCIgY2xhc3M9XCJjb2wtMS00XCI+XHJcbiAgICA8ZGl2IGNsYXNzPVwibW9kdWxlIGhlcm9cIj5cclxuICAgICAgPGg0Pnt7aGVyby5uYW1lfX08L2g0PlxyXG4gICAgPC9kaXY+XHJcbiAgPC9kaXY+XHJcbjwvZGl2PlxyXG48aGVyby1zZWFyY2g+PC9oZXJvLXNlYXJjaD5cclxuIiwiPG15LWRhc2hib2FyZD48L215LWRhc2hib2FyZD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0VFO01BQUE7SUFBQTtJQUFBO01BQUE7TUFBQTtJQUFBO0lBQUE7RUFBQSx1Q0FBQTt3QkFBQTtNQUFBLHFDQUFpQyxJQUFvRDtNQUNuRjtVQUFBO01BQXlCLDZDQUN2QjtVQUFBO1VBQUEsOEJBQUksd0NBQWtCO2lCQUFBLDRCQUNsQjs7UUFIeUI7UUFBakMsV0FBaUMsU0FBakM7O1FBRVE7UUFBQTs7OztvQkFKVjtNQUFBLHdFQUFJO2FBQUEsZ0NBQWU7TUFDbkI7VUFBQTtNQUEyQix5Q0FDekI7VUFBQSxpRUFBQTtVQUFBO1VBQUEsdUNBSU07TUFDRix1Q0FDTjtVQUFBO3lFQUFBO1VBQUEsMEVBQUE7VUFBQTtVQUFBLDZCQUEyQjs7O0lBTnBCO0lBQUwsV0FBSyxTQUFMO0lBTUY7Ozs7b0JDUkE7TUFBQTttQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
