/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './hero-search.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './hero-search.component';
import * as i3 from '@angular/common';
import * as i4 from './hero-search.service';
import * as i5 from '@angular/http';
import * as i6 from '@angular/router';
const styles_HeroSearchComponent:any[] = [i0.styles];
export const RenderType_HeroSearchComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_HeroSearchComponent,data:{}});
function View_HeroSearchComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'div',[['class',
      'search-result']],(null as any),[[(null as any),'click']],(_v,en,$event) => {
    var ad:boolean = true;
    var _co:any = _v.component;
    if (('click' === en)) {
      const pd_0:any = ((<any>_co.gotoDetail(_v.context.$implicit)) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n      ','\n    ']))],
      (null as any),(_ck,_v) => {
        const currVal_0:any = _v.context.$implicit.name;
        _ck(_v,1,0,currVal_0);
      });
}
export function View_HeroSearchComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),13,'div',[['id',
      'search-component']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),1,'h4',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['Hero Search'])),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,[['searchBox',1]],
          (null as any),0,'input',[['id','search-box']],(null as any),[[(null as any),
              'keyup']],(_v,en,$event) => {
            var ad:boolean = true;
            var _co:i2.HeroSearchComponent = _v.component;
            if (('keyup' === en)) {
              const pd_0:any = ((<any>_co.search(i1.ɵnov(_v,5).value)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n  '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),5,'div',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵand(16777216,(null as any),(null as any),2,(null as any),
          View_HeroSearchComponent_1)),i1.ɵdid(802816,(null as any),0,i3.NgForOf,[i1.ViewContainerRef,
          i1.TemplateRef,i1.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any)),
      i1.ɵpid(131072,i3.AsyncPipe,[i1.ChangeDetectorRef]),(_l()(),i1.ɵted((null as any),
          ['\n  '])),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),
          ['\n']))],(_ck,_v) => {
    var _co:i2.HeroSearchComponent = _v.component;
    const currVal_0:any = i1.ɵunv(_v,10,0,i1.ɵnov(_v,11).transform(_co.heroes));
    _ck(_v,10,0,currVal_0);
  },(null as any));
}
export function View_HeroSearchComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),2,'hero-search',
      ([] as any[]),(null as any),(null as any),(null as any),View_HeroSearchComponent_0,
      RenderType_HeroSearchComponent)),i1.ɵprd(512,(null as any),i4.HeroSearchService,
      i4.HeroSearchService,[i5.Http]),i1.ɵdid(114688,(null as any),0,i2.HeroSearchComponent,
      [i4.HeroSearchService,i6.Router],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,2,0);
  },(null as any));
}
export const HeroSearchComponentNgFactory:i1.ComponentFactory<i2.HeroSearchComponent> = i1.ɵccf('hero-search',
    i2.HeroSearchComponent,View_HeroSearchComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvcnN1YnJhbWFuaWFuL0RvY3VtZW50cy9Bbmd1bGFyVHJhaW5pbmcvV2syL2kxOG5OZXcvc3JjL2FwcC9oZXJvLXNlYXJjaC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvcnN1YnJhbWFuaWFuL0RvY3VtZW50cy9Bbmd1bGFyVHJhaW5pbmcvV2syL2kxOG5OZXcvc3JjL2FwcC9oZXJvLXNlYXJjaC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9yc3VicmFtYW5pYW4vRG9jdW1lbnRzL0FuZ3VsYXJUcmFpbmluZy9XazIvaTE4bk5ldy9zcmMvYXBwL2hlcm8tc2VhcmNoLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvcnN1YnJhbWFuaWFuL0RvY3VtZW50cy9Bbmd1bGFyVHJhaW5pbmcvV2syL2kxOG5OZXcvc3JjL2FwcC9oZXJvLXNlYXJjaC5jb21wb25lbnQudHMuSGVyb1NlYXJjaENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgaWQ9XCJzZWFyY2gtY29tcG9uZW50XCI+XHJcbiAgPGg0Pkhlcm8gU2VhcmNoPC9oND5cclxuICA8aW5wdXQgI3NlYXJjaEJveCBpZD1cInNlYXJjaC1ib3hcIiAoa2V5dXApPVwic2VhcmNoKHNlYXJjaEJveC52YWx1ZSlcIiAvPlxyXG4gIDxkaXY+XHJcbiAgICA8ZGl2ICpuZ0Zvcj1cImxldCBoZXJvIG9mIGhlcm9lcyB8IGFzeW5jXCJcclxuICAgICAgICAgKGNsaWNrKT1cImdvdG9EZXRhaWwoaGVybylcIiBjbGFzcz1cInNlYXJjaC1yZXN1bHRcIiA+XHJcbiAgICAgIHt7aGVyby5uYW1lfX1cclxuICAgIDwvZGl2PlxyXG4gIDwvZGl2PlxyXG48L2Rpdj5cclxuIiwiPGhlcm8tc2VhcmNoPjwvaGVyby1zZWFyY2g+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNJSTtNQUFBO0lBQUE7SUFBQTtJQUNLO01BQUE7TUFBQTtJQUFBO0lBREw7RUFBQSxnQ0FDdUQ7O1FBQUE7UUFBQTs7OztvQkFMM0Q7TUFBQTtNQUFBLGdCQUEyQix5Q0FDekI7TUFBQTtNQUFBLDhCQUFJO01BQWdCLHlDQUNwQjtVQUFBO2NBQUE7WUFBQTtZQUFBO1lBQWtDO2NBQUE7Y0FBQTtZQUFBO1lBQWxDO1VBQUEsZ0NBQXNFO01BQ3RFO1VBQUEsMERBQUs7VUFBQSxhQUNIO1VBQUEsb0NBQUE7MkNBQUE7YUFBSyw2Q0FHQztVQUFBLFdBQ0YsdUNBQ0Y7VUFBQTs7SUFMRztJQUFMLFlBQUssU0FBTDs7OztvQkNKSjtNQUFBO29DQUFBOzJCQUFBLGtCQUFBO01BQUE7SUFBQTs7OzsifQ==
