/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.search-result[_ngcontent-%COMP%]{\r\n  border-bottom: 1px solid gray;\r\n  border-left: 1px solid gray;\r\n  border-right: 1px solid gray;\r\n  width:195px;\r\n  height: 16px;\r\n  padding: 5px;\r\n  background-color: white;\r\n  cursor: pointer;\r\n}\r\n\r\n.search-result[_ngcontent-%COMP%]:hover {\r\n  color: #eee;\r\n  background-color: #607D8B;\r\n}\r\n\r\n#search-box[_ngcontent-%COMP%]{\r\n  width: 200px;\r\n  height: 20px;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvcnN1YnJhbWFuaWFuL0RvY3VtZW50cy9Bbmd1bGFyVHJhaW5pbmcvV2syL2kxOG5OZXcvc3JjL2FwcC9oZXJvLXNlYXJjaC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL3JzdWJyYW1hbmlhbi9Eb2N1bWVudHMvQW5ndWxhclRyYWluaW5nL1drMi9pMThuTmV3L3NyYy9hcHAvaGVyby1zZWFyY2guY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
